/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author ticok
 */
public class RealizarPagamentoView extends javax.swing.JFrame {

    /**
     * Creates new form RealizarPagamentoView2
     */
    public RealizarPagamentoView() {
        initComponents();
    }

    public JButton getCreditoBtn() {
        return creditoBtn;
    }

    public JButton getDebitoBtn() {
        return debitoBtn;
    }

    public JButton getDinheiroBtn() {
        return dinheiroBtn;
    }

    public JButton getPixBtn() {
        return pixBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dinheiroBtn = new javax.swing.JButton();
        pixBtn = new javax.swing.JButton();
        debitoBtn = new javax.swing.JButton();
        creditoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dinheiroBtn.setText("Dinheiro");

        pixBtn.setText("PIX");

        debitoBtn.setText("Débito");

        creditoBtn.setText("Crédito");

        jLabel1.setText("Escolha uma forma de pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dinheiroBtn)
                        .addGap(18, 18, 18)
                        .addComponent(pixBtn)
                        .addGap(41, 41, 41)
                        .addComponent(debitoBtn)
                        .addGap(27, 27, 27)
                        .addComponent(creditoBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinheiroBtn)
                    .addComponent(pixBtn)
                    .addComponent(debitoBtn)
                    .addComponent(creditoBtn))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditoBtn;
    private javax.swing.JButton debitoBtn;
    private javax.swing.JButton dinheiroBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pixBtn;
    // End of variables declaration//GEN-END:variables
}
