/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Pedro
 */
public class ListarReqsView extends javax.swing.JFrame {

    /**
     * Creates new form ListarReqsView
     */
    public ListarReqsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbReqs = new javax.swing.JTable();
        AddReqsBtn = new javax.swing.JButton();
        AtualizaTableBtn = new javax.swing.JButton();
        ExcluirReqsBtn = new javax.swing.JButton();
        SelecionarMesaControllerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbReqs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbReqs);

        AddReqsBtn.setText("Adicionar");

        AtualizaTableBtn.setText("Atualizar");

        ExcluirReqsBtn.setText("Excluir");

        SelecionarMesaControllerBtn.setText("Selecionar Mesa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddReqsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AtualizaTableBtn)
                .addGap(28, 28, 28)
                .addComponent(ExcluirReqsBtn)
                .addGap(27, 27, 27)
                .addComponent(SelecionarMesaControllerBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddReqsBtn)
                    .addComponent(AtualizaTableBtn)
                    .addComponent(ExcluirReqsBtn)
                    .addComponent(SelecionarMesaControllerBtn))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAddReqsBtn() {
        return AddReqsBtn;
    }

    public JButton getAtualizaTableBtn() {
        return AtualizaTableBtn;
    }

    public JButton getExcluirReqsBtn() {
        return ExcluirReqsBtn;
    }

    public JTable getTbReqs() {
        return tbReqs;
    }

    public JButton getSelecionarMesaControllerBtn() {
        return SelecionarMesaControllerBtn;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddReqsBtn;
    private javax.swing.JButton AtualizaTableBtn;
    private javax.swing.JButton ExcluirReqsBtn;
    private javax.swing.JButton SelecionarMesaControllerBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbReqs;
    // End of variables declaration//GEN-END:variables
}
